# Week 3 Pre-Class: Exploring the Healthcare Dataset

## I 320D: Data Science for Biomedical Informatics
**Instructor:** Ammar Darkazanli  
**Spring 2026**

---

### 🎯 This Week's Mantra

# "Every Column Tells a Story"

*Translation: Domain context and metadata are essential for valid analysis.*

---

### Video Sections
| Part | Topic | Timestamp |
|------|-------|----------|
| 1 | Introduction | 0:00 |
| 2 | Understanding Kaggle | 3:00 |
| 3 | Meet the Dataset | 10:00 |
| 4 | Research Your Columns | 15:00 |
| 5 | Creating Groups | 22:00 |
| 6 | Good Questions | 30:00 |
| 7 | Your Turn | 35:00 |

---
# PART 1: Introduction (0:00 - 3:00)
---

**Key Points to Cover:**
- Last week: "Before you analyze, you must organize"
- This week: "Every Column Tells a Story"
- We're using a real healthcare dataset from Kaggle
- First, let's learn how to navigate Kaggle

---
# PART 2: Understanding Kaggle (3:00 - 10:00)
---

**[SWITCH TO BROWSER - LIVE DEMO]**

### Demo Steps:
1. Go to kaggle.com/datasets
2. Search for "healthcare"
3. Show filters (usability score, file type, size)
4. Click on a dataset → show Data Card
5. Show the **Data** tab (column preview, data types)

### What to Point Out:
- **Data Card** = the dataset's resume
- **Usability Score** = quality indicator (aim for 8+)
- **Data tab** = preview columns and types BEFORE downloading
- **Notebooks tab** = see how others have used the data

### 💡 Why Synthetic Data? Understanding HIPAA

Real healthcare data is protected by **HIPAA** (Health Insurance Portability and Accountability Act of 1996). HIPAA is a federal law that regulates how Protected Health Information (PHI) can be used and shared.

**Protected Health Information (PHI) includes:**
- Names
- Addresses (anything more specific than state)
- Dates (except year) — includes birth dates, admission dates, discharge dates, death dates
- Phone numbers
- Email addresses
- Social Security numbers
- Medical record numbers
- Any unique identifying characteristic

**Why this matters for data science:**
- You cannot access real patient data without proper authorization and training
- Before working with real healthcare data in your career, you'll complete HIPAA training (typically 2-4 hours)
- Violations can result in significant fines ($100 - $50,000+ per violation)

Using synthetic data lets us learn the same analytical skills without privacy concerns or IRB (Institutional Review Board) approval requirements.

---
# PART 3: Meet the Dataset (10:00 - 15:00)
---

Now let's load our healthcare dataset and see what we're working with.

In [1]:
# Import libraries
import pandas as pd
import numpy as np

# Set display options for better readability
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', 50)

In [2]:
# Load the dataset
df = pd.read_csv('healthcare_dataset.csv')

# First look - what do we have?
print("="*60)
print("DATASET OVERVIEW")
print("="*60)
print(f"\n📊 Shape: {df.shape[0]:,} rows × {df.shape[1]} columns")
print(f"\n📋 Columns:")
for i, col in enumerate(df.columns, 1):
    print(f"   {i:2}. {col}")

============================================================
DATASET OVERVIEW
============================================================

📊 Shape: 55,500 rows × 15 columns

📋 Columns:
    1. Name
    2. Age
    3. Gender
    4. Blood Type
    5. Medical Condition
    6. Date of Admission
    7. Doctor
    8. Hospital
    9. Insurance Provider
   10. Billing Amount
   11. Room Number
   12. Admission Type
   13. Discharge Date
   14. Medication
   15. Test Results

### 💬 Talking Point
> "55,500 rows and 15 columns. Each row is one patient admission. Each column is one piece of information about that admission. But here's the key question: **What does each column actually mean?**"

In [3]:
# Let's see the first few rows
print("\n📝 First 5 Rows:")
df.head()

📝 First 5 Rows:

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,Bobby JacksOn,30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,328,Urgent,2024-02-02,Paracetamol,Normal
1,LesLie TErRy,62,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327287,265,Emergency,2019-08-26,Ibuprofen,Inconclusive
2,DaNnY sMitH,76,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.096079,205,Emergency,2022-10-07,Aspirin,Normal
3,andrEw waTtS,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.782410,450,Elective,2020-12-18,Ibuprofen,Abnormal
4,adrIENNE bEll,43,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.317814,458,Urgent,2022-10-09,Penicillin,Abnormal

In [4]:
# Data types - what kind of data is in each column?
print("\n🔤 Data Types:")
print(df.dtypes)

🔤 Data Types:
Name                   object
Age                     int64
Gender                 object
Blood Type             object
Medical Condition      object
Date of Admission      object
Doctor                 object
Hospital               object
Insurance Provider     object
Billing Amount        float64
Room Number             int64
Admission Type         object
Discharge Date         object
Medication             object
Test Results           object
dtype: object

### Understanding Feature Types

Before we dive into the columns, let's understand the different types of features you'll encounter. **This is crucial for choosing the right analysis methods.**

| Feature Type | Definition | Examples in Our Dataset |
|--------------|------------|------------------------|
| **Continuous** | Numeric values that can take any value within a range | Billing Amount, Age |
| **Discrete** | Numeric values that are countable integers | Room Number, Length of Stay |
| **Categorical (Nominal)** | Categories with no inherent order | Gender, Blood Type, Hospital, Doctor |
| **Ordinal** | Categories with meaningful order | Test Results (Normal < Abnormal), Admission Type (by acuity) |
| **DateTime** | Date and/or time values | Date of Admission, Discharge Date |
| **Identifier** | Unique identifiers, typically not used for analysis | Name (if used as ID) |

### ⚠️ Why Feature Types Matter

You can't calculate the mean of a categorical variable, and you shouldn't treat ordinal data as purely numeric. Knowing your feature types guides which statistical methods and visualizations are appropriate.

### The 15 Columns Organized

| Category | Columns | What They Capture |
|----------|---------|-------------------|
| **Patient Demographics** | Name, Age, Gender, Blood Type | Who the patient is |
| **Clinical Information** | Medical Condition, Medication, Test Results | What's being treated and how |
| **Admission Details** | Date of Admission, Discharge Date, Admission Type | When and how they entered the hospital |
| **Care Providers** | Doctor, Hospital | Who provided care and where |
| **Administrative** | Insurance Provider, Billing Amount, Room Number | The business side of healthcare |

**Note:** You might organize these differently—that's okay! The point is imposing structure.

---
# PART 4: Research Your Columns (15:00 - 22:00)
---

## 🔍 How to Research a Column:

1. Check the Kaggle Data Card (if available)
2. Examine the data: `df['ColumnName'].describe()` or `.value_counts()`
3. Check unique values and ranges
4. Google it: "healthcare admission type meaning"
5. Ask in Slack if still unsure

### Data Validation: Check Before You Analyze

Before diving into analysis, **always validate your data**. Here's a validation checklist:

In [5]:
# === DATA VALIDATION CHECKS ===

print("--- Age Validation ---")
print(f"Ages below 0: {(df['Age'] < 0).sum()}")
print(f"Ages above 120: {(df['Age'] > 120).sum()}")
print(f"Age range: {df['Age'].min()} to {df['Age'].max()}")
print(f"Mean age: {df['Age'].mean():.1f}")

print("\n--- Billing Validation ---")
print(f"Negative billing amounts: {(df['Billing Amount'] < 0).sum()}")
print(f"Zero billing amounts: {(df['Billing Amount'] == 0).sum()}")

# Create a filtered dataframe of negative values sorted from most negative to least negative
negative_bills_sorted = df[df['Billing Amount'] < 0].sort_values(by='Billing Amount', ascending=True)

print("\n--- Negative Billing Records (Most Negative First) ---")
if not negative_bills_sorted.empty:
    # Displaying Name, Medical Condition, and Billing Amount for these records
    print(negative_bills_sorted[['Name', 'Medical Condition', 'Billing Amount']])
else:
    print("No negative billing amounts found.")

# Create a list of all rows with negative billing amounts
negative_billing_df = df[df['Billing Amount'] < 0]

print("\n--- List of Negative Billing Records ---")
if not negative_billing_df.empty:
    # Displaying the first few to avoid clutter, or remove .head() to see all 108
    print(negative_billing_df[['Name', 'Medical Condition', 'Billing Amount']].head(10))
else:
    print("No negative billing amounts found.")

# Create a list of all rows with negative billing amounts
negative_billing_df = df[df['Billing Amount'] < 0]


print("\n--- Date Validation ---")
# Convert dates with error handling
# IMPORTANT: errors='coerce' converts unparseable dates to NaT (Not a Time)
# instead of raising an error. Always check how many values failed to parse!
df['Date of Admission'] = pd.to_datetime(df['Date of Admission'], errors='coerce')
df['Discharge Date'] = pd.to_datetime(df['Discharge Date'], errors='coerce')

# Check for parsing failures
print(f"Failed date parsing (Admission): {df['Date of Admission'].isna().sum()}")
print(f"Failed date parsing (Discharge): {df['Discharge Date'].isna().sum()}")

# Check for logical issues
df['LengthOfStay'] = (df['Discharge Date'] - df['Date of Admission']).dt.days
print(f"Negative length of stay: {(df['LengthOfStay'] < 0).sum()}")
print(f"Same-day discharges: {(df['LengthOfStay'] == 0).sum()}")

--- Age Validation ---
Ages below 0: 0
Ages above 120: 0
Age range: 13 to 89
Mean age: 51.5

--- Billing Validation ---
Negative billing amounts: 108
Zero billing amounts: 0

--- Negative Billing Records (Most Negative First) ---
                  Name Medical Condition  Billing Amount
47589       james lUnA            Cancer    -2008.492140
48659      EMMA savAGE      Hypertension    -1660.009373
42621        joHn hahN            Asthma    -1520.420555
44040   JOsEPH robBins      Hypertension    -1428.843941
29484     tErRy WILSOn          Diabetes    -1316.618581
...                ...               ...             ...
44565     DAnIeL DAViD           Obesity      -36.217270
21275  JoSEPH marTInez            Asthma      -32.348729
14534    LiSA rOBInSoN         Arthritis      -26.112523
50369    LiSA rOBInSoN         Arthritis      -26.112523
32873     meLissA diAz      Hypertension      -23.866729

[108 rows x 3 columns]

--- List of Negative Billing Records ---
                          Name Medical Condition  Billing Amount
132            ashLEy ERIcKSoN            Cancer     -502.507813
799          CHRisTOPHer wEiss            Asthma    -1018.245371
1018             AsHley WaRnER      Hypertension     -306.364925
1421              JAY galloWaY            Asthma     -109.097122
2103         josHUa wilLIamSon          Diabetes     -576.727907
2696             Scott VaZqUEz          Diabetes     -135.986000
2855            CaROl aNDErSoN      Hypertension     -370.983674
3772  mr. ChRIStOPhER aLvARaDO           Obesity    -1310.272895
5445            ALExAndrA KHaN         Arthritis     -692.408820
5708                JosEPh cOx          Diabetes     -353.865186

--- Date Validation ---
Failed date parsing (Admission): 0
Failed date parsing (Discharge): 0
Negative length of stay: 0
Same-day discharges: 0

### ⚠️ IMPORTANT: The `errors='coerce'` Parameter

The `errors='coerce'` parameter in `pd.to_datetime()` converts unparseable dates to `NaT` (Not a Time) instead of raising an error. 

**Always check how many values failed to parse!** If you see unexpected NaT values, investigate why those dates couldn't be parsed.

### Example 1: Investigating "Medical Condition"

In [6]:
# What medical conditions are in our dataset?
print("Medical Conditions in Dataset:")
print("="*40)
print(df['Medical Condition'].value_counts())

Medical Conditions in Dataset:
========================================
Medical Condition
Arthritis       9308
Diabetes        9304
Hypertension    9245
Obesity         9231
Cancer          9227
Asthma          9185
Name: count, dtype: int64

### 💬 Talking Point
> "Six conditions: Arthritis, Diabetes, Hypertension, Obesity, Cancer, and Asthma. These are common chronic conditions. But ask yourself:"

**Questions to consider:**
- Is this the PRIMARY diagnosis or just one of many?
- Are these mutually exclusive? (Can a patient have both diabetes AND hypertension?)
- How were these diagnosed? ICD codes? Self-reported?

### Example 2: Investigating "Admission Type"

In [7]:
# What admission types are there?
print("Admission Types in Dataset:")
print("="*40)
print(df['Admission Type'].value_counts())

Admission Types in Dataset:
========================================
Admission Type
Elective     18655
Urgent       18576
Emergency    18269
Name: count, dtype: int64

### 💬 Talking Point
> "Elective, Urgent, and Emergency. These are standard healthcare admission categories:"

| Type | Definition | Example |
|------|------------|--------|
| **Elective** | Planned in advance | Scheduled surgery, routine procedure |
| **Urgent** | Needs attention soon, not immediately life-threatening | Worsening symptoms, infection |
| **Emergency** | Immediate, unplanned | Accident, heart attack, stroke |

### Example 3: Investigating "Age"

In [8]:
# Age distribution
print("Age Statistics:")
print("="*40)
print(df['Age'].describe())
print(f"\nMin Age: {df['Age'].min()}")
print(f"Max Age: {df['Age'].max()}")

Age Statistics:
========================================
count    55500.000000
mean        51.539459
std         19.602454
min         13.000000
25%         35.000000
50%         52.000000
75%         68.000000
max         89.000000
Name: Age, dtype: float64

Min Age: 13
Max Age: 89

### Example 4: Investigating "Billing Amount"

In [9]:
# Billing Amount distribution
print("Billing Amount Statistics:")
print("="*40)
print(df['Billing Amount'].describe())
print(f"\nMin: ${df['Billing Amount'].min():,.2f}")
print(f"Max: ${df['Billing Amount'].max():,.2f}")

Billing Amount Statistics:
========================================
count    55500.000000
mean     25539.316097
std      14211.454431
min      -2008.492140
25%      13241.224652
50%      25538.069376
75%      37820.508436
max      52764.276736
Name: Billing Amount, dtype: float64

Min: $-2,008.49
Max: $52,764.28

### ⚠️ Cautionary Tale

> "Notice there are **negative** billing amounts! What could that mean?"

Possible explanations:
- Billing adjustments or corrections
- Insurance overpayments being refunded
- Data entry errors

**This is why we investigate columns before analyzing!**

In [10]:
# How many negative billing amounts?
negative_bills = df[df['Billing Amount'] < 0]
print(f"Negative billing amounts: {len(negative_bills):,} ({len(negative_bills)/len(df)*100:.2f}%)")

Negative billing amounts: 108 (0.19%)

### Example 5: Investigating "Test Results"

In [11]:
# Test Results categories
print("Test Results Categories:")
print("="*40)
print(df['Test Results'].value_counts())
print("\nAs percentages:")
print(df['Test Results'].value_counts(normalize=True).round(3) * 100)

Test Results Categories:
========================================
Test Results
Abnormal        18627
Normal          18517
Inconclusive    18356
Name: count, dtype: int64

As percentages:
Test Results
Abnormal        33.6
Normal          33.4
Inconclusive    33.1
Name: proportion, dtype: float64

### 💬 Talking Point
> "Normal, Abnormal, and Inconclusive. But what TEST? Blood work? Imaging? This is where the Data Card would help—or we'd need to ask the data provider."

### Quick Summary: All Categorical Columns

In [12]:
# Let's see all categorical columns at once
categorical_cols = ['Gender', 'Blood Type', 'Medical Condition', 
                    'Insurance Provider', 'Admission Type', 
                    'Medication', 'Test Results']

print("CATEGORICAL COLUMN SUMMARY")
print("="*60)
for col in categorical_cols:
    print(f"\n📊 {col}:")
    print(df[col].value_counts())
    print("-"*40)

CATEGORICAL COLUMN SUMMARY
============================================================

📊 Gender:
Gender
Male      27774
Female    27726
Name: count, dtype: int64
----------------------------------------

📊 Blood Type:
Blood Type
A-     6969
A+     6956
AB+    6947
AB-    6945
B+     6945
B-     6944
O+     6917
O-     6877
Name: count, dtype: int64
----------------------------------------

📊 Medical Condition:
Medical Condition
Arthritis       9308
Diabetes        9304
Hypertension    9245
Obesity         9231
Cancer          9227
Asthma          9185
Name: count, dtype: int64
----------------------------------------

📊 Insurance Provider:
Insurance Provider
Cigna               11249
Medicare            11154
UnitedHealthcare    11125
Blue Cross          11059
Aetna               10913
Name: count, dtype: int64
----------------------------------------

📊 Admission Type:
Admission Type
Elective     18655
Urgent       18576
Emergency    18269
Name: count, dtype: int64
----------------------------------------

📊 Medication:
Medication
Lipitor        11140
Ibuprofen      11127
Aspirin        11094
Paracetamol    11071
Penicillin     11068
Name: count, dtype: int64
----------------------------------------

📊 Test Results:
Test Results
Abnormal        18627
Normal          18517
Inconclusive    18356
Name: count, dtype: int64
----------------------------------------

---
# ⏸️ GOOD STOPPING POINT
---

If you need a break, this is a good place to pause the video.

**So far you've learned:**
- How to navigate Kaggle
- What a Data Card is
- Why we use synthetic data (HIPAA!)
- Feature types and why they matter
- How to validate data quality
- How to investigate individual columns
- Why context matters (admission types, billing anomalies)

**Coming up:** Creating groups and comparing them

---
# PART 5: Creating Data Groups (22:00 - 30:00)
---

### ⚠️ THIS IS THE CODE-HEAVY SECTION

If you find it overwhelming, focus on the **CONCEPT** (why we group data) rather than memorizing the code. You can always copy from the appendix.

## "Divide and Understand"

One of the most powerful things you can do with data is:
1. Create meaningful groups
2. Compare them

**Our Question:** Do older patients have different outcomes than younger patients?

### Clinically-Relevant Age Groups

When creating age groups, we should use **clinically meaningful categories**. Here are standard clinical age groupings:

| Age Group | Range | Clinical Rationale |
|-----------|-------|--------------------|
| **Pediatric** | Under 18 | Different physiology, parental consent required |
| **Young Adult** | 18-39 | Generally healthier baseline, few chronic conditions |
| **Middle-Aged** | 40-64 | Onset of chronic conditions, preventive screening age |
| **Senior** | 65+ | Medicare eligibility, higher complexity, geriatric considerations |

**💡 NOTE:** If your dataset includes patients under 18, add a "Pediatric" category (0-17). The key is choosing boundaries that have **clinical meaning**, not arbitrary round numbers.

### Step 1: Understand the Age Distribution

In [13]:
# What ages do we have?
print("Age Distribution:")
print("="*40)
print(df['Age'].describe())
print(f"\nRange: {df['Age'].min()} to {df['Age'].max()} years old")

Age Distribution:
========================================
count    55500.000000
mean        51.539459
std         19.602454
min         13.000000
25%         35.000000
50%         52.000000
75%         68.000000
max         89.000000
Name: Age, dtype: float64

Range: 13 to 89 years old

### 💬 Talking Point
> "Our patients range from the minimum to maximum ages in the dataset. That's a wide range! Comparing every single age would be overwhelming. Instead, let's create **clinically meaningful groups**."

### Three Ways to Create Groups

I'll show you three methods. **Method 1 is most readable** for learning. Methods 2 and 3 are shortcuts you might prefer later.

#### METHOD 1: Custom Function (Most Readable)

In [14]:
# Method 1: Custom function - explicit and readable
def categorize_age_clinical(age):
    """Clinically-aligned age grouping."""
    if age < 18:
        return 'Pediatric (Under 18)'
    elif age <= 39:
        return 'Young Adult (18-39)'
    elif age <= 64:
        return 'Middle-Aged (40-64)'
    else:
        return 'Senior (65+)'

# Apply the function to create a new column
df['AgeGroup'] = df['Age'].apply(categorize_age_clinical)

print("Age Groups Created (Method 1 - Clinical Categories):")
print(df['AgeGroup'].value_counts())
df.head()

Age Groups Created (Method 1 - Clinical Categories):
AgeGroup
Middle-Aged (40-64)     20541
Young Adult (18-39)     17756
Senior (65+)            17087
Pediatric (Under 18)      116
Name: count, dtype: int64

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results,LengthOfStay,AgeGroup
0,Bobby JacksOn,30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,328,Urgent,2024-02-02,Paracetamol,Normal,2,Young Adult (18-39)
1,LesLie TErRy,62,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327287,265,Emergency,2019-08-26,Ibuprofen,Inconclusive,6,Middle-Aged (40-64)
2,DaNnY sMitH,76,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.096079,205,Emergency,2022-10-07,Aspirin,Normal,15,Senior (65+)
3,andrEw waTtS,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.782410,450,Elective,2020-12-18,Ibuprofen,Abnormal,30,Young Adult (18-39)
4,adrIENNE bEll,43,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.317814,458,Urgent,2022-10-09,Penicillin,Abnormal,20,Middle-Aged (40-64)

#### METHOD 2: np.where (For Binary Splits)

In [15]:
# Method 2: np.where - good for simple binary splits
df['IsSenior'] = np.where(df['Age'] >= 65, 'Senior', 'Non-Senior')

print("Binary Age Groups (Method 2):")
print(df['IsSenior'].value_counts())

Binary Age Groups (Method 2):
IsSenior
Non-Senior    38413
Senior        17087
Name: count, dtype: int64

#### METHOD 3: pd.cut (Best for Multiple Groups)

In [16]:
# Method 3: pd.cut - powerful for multiple bins
# IMPORTANT: pd.cut uses LEFT-EXCLUSIVE intervals by default
# bins=[0, 17, 39, 64, 100] creates: (0,17], (17,39], (39,64], (64,100]
# Use include_lowest=True to make first bin inclusive: [0,17]

df['AgeGroup_cut'] = pd.cut(
    df['Age'],
    bins=[0, 17, 39, 64, 100],
    labels=['Pediatric', 'Young Adult', 'Middle-Aged', 'Senior'],
    include_lowest=True  # CRITICAL: Makes first bin [0,17] instead of (0,17]
)

print("Age Groups Created (Method 3 - pd.cut):")
print(df['AgeGroup_cut'].value_counts())

Age Groups Created (Method 3 - pd.cut):
AgeGroup_cut
Middle-Aged    20541
Young Adult    17756
Senior         17087
Pediatric        116
Name: count, dtype: int64

### ⚠️ TECHNICAL NOTE on pd.cut()

By default, `pd.cut()` creates intervals that are **left-exclusive and right-inclusive**: `(a, b]`

This means the **left boundary is NOT included**.

**Always use `include_lowest=True`** when your data might include the minimum value, or values at the left boundary will become NaN!

| Without `include_lowest=True` | With `include_lowest=True` |
|------------------------------|---------------------------|
| `(0, 17]` — excludes 0 | `[0, 17]` — includes 0 |
| Age 0 → NaN | Age 0 → 'Pediatric' |

### 💬 Talking Point
> "All three methods produce similar results. Method 1 is most explicit—you can see exactly what's happening. But as you get comfortable, `pd.cut()` is what you'll use most because it handles multiple groups elegantly. Just remember the `include_lowest=True` parameter!"

### Step 3: Compare the Groups

Now the magic happens—let's ask questions and get answers!

In [17]:
# Compare average billing amount by age group
print("💰 Average Billing Amount by Age Group:")
print("="*50)
billing_by_age = df.groupby('AgeGroup')['Billing Amount'].agg(['mean', 'median', 'std']).round(2)
billing_by_age.columns = ['Mean ($)', 'Median ($)', 'Std Dev ($)']
print(billing_by_age)

💰 Average Billing Amount by Age Group:
==================================================
                      Mean ($)  Median ($)  Std Dev ($)
AgeGroup
Middle-Aged (40-64)   25560.06    25737.39     14251.37
Pediatric (Under 18)  28512.86    30050.64     13827.05
Senior (65+)          25421.03    25428.30     14185.51
Young Adult (18-39)   25609.72    25367.14     14191.10

In [18]:
# Compare admission types by age group
print("\n🏥 Admission Type by Age Group (% within each group):")
print("="*60)
admission_by_age = pd.crosstab(df['AgeGroup'], df['Admission Type'], normalize='index').round(3) * 100
print(admission_by_age)

🏥 Admission Type by Age Group (% within each group):
============================================================
Admission Type        Elective  Emergency  Urgent
AgeGroup
Middle-Aged (40-64)       34.1       32.5    33.4
Pediatric (Under 18)      29.3       41.4    29.3
Senior (65+)              33.0       33.3    33.7
Young Adult (18-39)       33.8       32.9    33.3

In [19]:
# Compare test results by age group
print("\n🔬 Test Results by Age Group (% within each group):")
print("="*60)
results_by_age = pd.crosstab(df['AgeGroup'], df['Test Results'], normalize='index').round(3) * 100
print(results_by_age)

🔬 Test Results by Age Group (% within each group):
============================================================
Test Results          Abnormal  Inconclusive  Normal
AgeGroup
Middle-Aged (40-64)       33.8          33.5    32.7
Pediatric (Under 18)      40.5          28.4    31.0
Senior (65+)              33.5          33.1    33.4
Young Adult (18-39)       33.2          32.6    34.1

In [20]:
# Compare medical conditions by age group
print("\n🩺 Medical Conditions by Age Group (% within each group):")
print("="*60)
conditions_by_age = pd.crosstab(df['AgeGroup'], df['Medical Condition'], normalize='index').round(3) * 100
print(conditions_by_age)

🩺 Medical Conditions by Age Group (% within each group):
============================================================
Medical Condition     Arthritis  Asthma  Cancer  Diabetes  Hypertension  \
AgeGroup
Middle-Aged (40-64)        16.6    16.2    16.5      17.1          16.6
Pediatric (Under 18)       18.1    17.2    18.1      13.8           9.5
Senior (65+)               16.9    16.9    16.6      16.6          16.8
Young Adult (18-39)        16.8    16.6    16.8      16.6          16.5

Medical Condition     Obesity
AgeGroup
Middle-Aged (40-64)      17.0
Pediatric (Under 18)     23.3
Senior (65+)             16.1
Young Adult (18-39)      16.7

### 💬 Talking Point
> "Now we can see patterns! Are seniors more likely to have emergency admissions? Do they have different medical conditions? This is the power of thoughtful data grouping."

### BONUS: Compare Length of Stay by Age Group

In [21]:
# We already calculated LengthOfStay during validation
print("📅 Length of Stay Statistics:")
print("="*40)
print(df['LengthOfStay'].describe())

📅 Length of Stay Statistics:
========================================
count    55500.000000
mean        15.509009
std          8.659600
min          1.000000
25%          8.000000
50%         15.000000
75%         23.000000
max         30.000000
Name: LengthOfStay, dtype: float64

In [22]:
# Compare length of stay by age group
print("\n📅 Average Length of Stay by Age Group:")
print("="*50)
los_by_age = df.groupby('AgeGroup')['LengthOfStay'].agg(['mean', 'median']).round(2)
los_by_age.columns = ['Mean (days)', 'Median (days)']
print(los_by_age)

📅 Average Length of Stay by Age Group:
==================================================
                      Mean (days)  Median (days)
AgeGroup
Middle-Aged (40-64)         15.55           16.0
Pediatric (Under 18)        15.32           16.0
Senior (65+)                15.59           16.0
Young Adult (18-39)         15.39           15.0

---
# PART 6: Good Questions vs. Great Questions (30:00 - 35:00)
---

Not all questions are created equal. Understanding what your data **CAN** and **CANNOT** tell you is what separates rigorous analysis from misleading conclusions.

### ✅ Questions This Dataset CAN Answer

- "Is there a **relationship** between age and billing amount?"
- "Do patients with different medical conditions have different **lengths of stay**?"
- "Are emergency admissions more common with certain **insurance providers**?"
- "What percentage of diabetic patients have **abnormal test results**?"

**Notice:** These are about relationships and patterns, not causes.

### ❌ Questions This Dataset CANNOT Answer

- "Does being older **CAUSE** higher medical bills?" (Correlation ≠ Causation!)
- "What treatment was most **effective**?" (No treatment outcome data)
- "**Why** did patients choose certain hospitals?" (No decision-making data)
- "What is the **socioeconomic status** of patients?" (Not measured)

### ⚠️ KEY INSIGHT

# Understanding what your data CANNOT tell you is just as important as knowing what it CAN tell you.

This prevents you from making claims your data doesn't support.

### Common Pitfalls in Healthcare Data Analysis

Watch out for these common mistakes:

#### 1. Simpson's Paradox
A trend in aggregated data can **reverse** when split into groups.

**Example:** Hospital A might appear to have higher mortality but actually treats sicker patients. Always **stratify by severity** when comparing outcomes.

#### 2. Confusing Correlation with Causation
"Patients with longer stays have higher bills" ≠ "Staying longer **causes** higher bills."

Both could be caused by **severity of illness**.

#### 3. Ignoring Selection Bias
**Who is in your dataset? Who is missing?**

Emergency patients differ systematically from elective patients. Don't compare them without acknowledging this.

#### 4. Ecological Fallacy
Conclusions about **groups** don't apply to **individuals**.

"Seniors have higher average bills" ≠ "Any individual senior will have high bills."

### Let's Answer a Question the Data CAN Answer

In [23]:
# Question: What percentage of diabetic patients have abnormal test results?
print("Question: What % of diabetic patients have abnormal test results?")
print("="*65)

# Filter to diabetic patients
diabetic = df[df['Medical Condition'] == 'Diabetes']
print(f"\nTotal diabetic patients: {len(diabetic):,}")

print("--- Diabetic Patient Distribution by Age Group ---")
print("=" * 50)

# Calculate counts and percentages
age_dist_counts = diabetic['AgeGroup'].value_counts()
age_dist_percent = (diabetic['AgeGroup'].value_counts(normalize=True) * 100).round(2)

# Combine into a clean summary table
age_summary = pd.DataFrame({
    'Patient Count': age_dist_counts,
    'Percentage (%)': age_dist_percent
})

print(age_summary)

# Test results for diabetic patients
diabetic_results = diabetic['Test Results'].value_counts(normalize=True).round(3) * 100
print(f"\nTest Results Distribution:")
print(diabetic_results)

Question: What % of diabetic patients have abnormal test results?
=================================================================

Total diabetic patients: 9,304
--- Diabetic Patient Distribution by Age Group ---
==================================================
                      Patient Count  Percentage (%)
AgeGroup
Middle-Aged (40-64)            3504           37.66
Young Adult (18-39)            2946           31.66
Senior (65+)                   2838           30.50
Pediatric (Under 18)             16            0.17

Test Results Distribution:
Test Results
Abnormal        34.0
Normal          33.2
Inconclusive    32.7
Name: proportion, dtype: float64

In [24]:
# Compare to other conditions
print("\nComparison: Abnormal Test Results by Medical Condition")
print("="*60)

abnormal_by_condition = df.groupby('Medical Condition')['Test Results'].apply(
    lambda x: (x == 'Abnormal').mean() * 100
).round(2)

print(abnormal_by_condition.sort_values(ascending=False))

Comparison: Abnormal Test Results by Medical Condition
============================================================
Medical Condition
Arthritis       34.25
Diabetes        34.05
Obesity         33.93
Cancer          33.79
Asthma          32.76
Hypertension    32.58
Name: Test Results, dtype: float64

---
# PART 7: Your Turn (35:00 - 37:00)
---

## Pre-Class Assignment

Before class, complete these **five tasks** (~90-110 minutes total). I've included time estimates so you can plan.

### Task 1: Explore Kaggle (~15 min)
- Go to kaggle.com and create a free account (if you haven't)
- Find the healthcare dataset we're using
- Read through the Data Card—note any information about data collection

### Task 2: Create Your Data Dictionary (~30-40 min)
- Complete the data dictionary template for all 15 columns
- Research what each column means clinically
- **Include the feature type for each column** (continuous, categorical, ordinal, etc.)

### Task 3: Validate Your Data (~10 min)
- Run the validation checks from this video
- Document any issues you find (negative values, missing data, illogical dates)

### Task 4: Create One Custom Group (~15-20 min)
- Pick a column and create meaningful groups using **clinically-relevant categories**
- Some ideas:
  - Age → Clinical age groups (using the 18-39, 40-64, 65+ boundaries)
  - Billing Amount → "Low" (<$10k), "Medium" ($10k-$30k), "High" (>$30k)
  - Length of Stay (calculate from dates) → Short (<3 days), Medium (3-7 days), Long (>7 days)

### Task 5: Write Three Questions (~10-15 min)
- Write down three questions you'd like to explore with this data
- Make sure they're questions **the data can actually answer!**

### Summary: Pre-Class Checklist

| ✓ | Task | Time |
|---|------|------|
| ☐ | Watch this video completely | 35 min |
| ☐ | Create Kaggle account and explore the platform | 10 min |
| ☐ | Load the Healthcare dataset in Jupyter | 5 min |
| ☐ | Run the 10-Point Inspection and validation checks | 15 min |
| ☐ | Create data dictionary with feature types for all 15 columns | 30-40 min |
| ☐ | Create one custom grouping using clinical categories | 15-20 min |
| ☐ | Write 3 questions the data can answer | 10-15 min |
| ☐ | Complete the Pre-Class Quiz on Canvas | 10 min |

### Minimum Understanding Checkpoint

If you can **explain what each column in the dataset represents**, **identify its feature type**, and **explain why someone might want to group data by age or admission type using clinically-relevant categories**, you're ready for class!

**📍 NOT THERE YET?** Rewatch Parts 3 and 5, or post a question in the class Slack before class.

---
# 📝 YOUR PRACTICE SECTION
---

Use the cells below to practice what you learned. Look for `# YOUR CODE HERE` comments.

### Practice 1: Investigate a Column You Haven't Explored

In [25]:
# YOUR CODE HERE: Investigate 'Insurance Provider' or 'Hospital' or 'Blood Type'
# Use .value_counts() for categorical columns
# Use .describe() for numeric columns

### Practice 2: Create a Billing Amount Grouping

In [26]:
# YOUR CODE HERE: Create a 'BillingGroup' column
# Suggestion: Low (<$10,000), Medium ($10,000-$30,000), High (>$30,000)
# Use any of the three methods shown above

### Practice 3: Compare Groups

In [27]:
# YOUR CODE HERE: Compare your new groups
# Example: df.groupby('BillingGroup')['Age'].mean()
# Or: pd.crosstab(df['BillingGroup'], df['Admission Type'], normalize='index')

### 🚀 CHALLENGE: Length of Stay Groups

In [28]:
# CHALLENGE: Create Length of Stay groups and analyze them
# 1. Create groups: Short (<3 days), Medium (3-7 days), Long (>7 days)
# 2. Compare billing amounts across these groups
# 3. Compare medical conditions across these groups

# YOUR CODE HERE:

---
# ✅ Summary: What You Learned
---

1. **How to navigate Kaggle** and evaluate datasets using Data Cards
2. **Why synthetic data** is used in healthcare education (HIPAA and PHI)
3. **Feature types** and why they matter for analysis
4. **How to validate data** before analysis (check for errors, impossible values)
5. **How to investigate columns** systematically
6. **Three methods to create groups** (custom function, np.where, pd.cut)
7. **The importance of `include_lowest=True`** in pd.cut()
8. **How to compare groups** using groupby and crosstab
9. **What questions data CAN and CANNOT answer**
10. **Common pitfalls** in healthcare data analysis

---

## Remember Our Mantra:

# "Every Column Tells a Story"

Your job is to figure out what that story is.

---

**See you in class!** 🎓

---
# APPENDIX: Complete Code Reference
---

Copy this into your Jupyter Notebook to follow along. Look for `# YOUR CODE HERE` and `# CHALLENGE` comments—these are places to experiment!

In [29]:
# ============================================
# COMPLETE CODE REFERENCE
# Week 3: Exploring the Healthcare Dataset
# Mantra: "Every Column Tells a Story"
# ============================================

import pandas as pd
import numpy as np

# Load data
df = pd.read_csv('healthcare_dataset.csv')

# ============================================
# STEP 1: Dataset Overview
# ============================================
print("=== DATASET OVERVIEW ===")
print(f"Shape: {df.shape}")
print(f"\nColumns: {df.columns.tolist()}")

# ============================================
# STEP 2: Data Validation
# ============================================
print("\n=== DATA VALIDATION ===")

# Age validation
print("--- Age Validation ---")
print(f"Age range: {df['Age'].min()} to {df['Age'].max()}")
print(f"Invalid ages (negative or >120): {((df['Age'] < 0) | (df['Age'] > 120)).sum()}")

# Billing validation
print("\n--- Billing Validation ---")
print(f"Negative billing: {(df['Billing Amount'] < 0).sum()}")
print(f"Zero billing: {(df['Billing Amount'] == 0).sum()}")

# Date validation - USE errors='coerce' TO HANDLE BAD DATES
print("\n--- Date Validation ---")
df['Date of Admission'] = pd.to_datetime(df['Date of Admission'], errors='coerce')
df['Discharge Date'] = pd.to_datetime(df['Discharge Date'], errors='coerce')
print(f"Failed date parsing: {df['Date of Admission'].isna().sum()}")
df['LengthOfStay'] = (df['Discharge Date'] - df['Date of Admission']).dt.days
print(f"Negative LOS: {(df['LengthOfStay'] < 0).sum()}")
print(f"Same-day discharge: {(df['LengthOfStay'] == 0).sum()}")

# ============================================
# STEP 3: Create Clinical Age Groups
# ============================================
print("\n=== CREATING AGE GROUPS ===")

# Method 1: Custom function with clinical categories
def categorize_age_clinical(age):
    """Clinically-aligned age grouping"""
    if age < 18:
        return 'Pediatric (Under 18)'
    elif age <= 39:
        return 'Young Adult (18-39)'
    elif age <= 64:
        return 'Middle-Aged (40-64)'
    else:
        return 'Senior (65+)'

df['AgeGroup'] = df['Age'].apply(categorize_age_clinical)
print("Age Group Distribution:")
print(df['AgeGroup'].value_counts())

# Method 2: np.where - for binary splits
df['IsSenior'] = np.where(df['Age'] >= 65, 'Senior', 'Non-Senior')

# Method 3: pd.cut with include_lowest=True
# df['AgeGroup'] = pd.cut(
#     df['Age'],
#     bins=[0, 17, 39, 64, 100],
#     labels=['Pediatric', 'Young Adult', 'Middle-Aged', 'Senior'],
#     include_lowest=True  # CRITICAL: includes the minimum value
# )

# ============================================
# STEP 4: Compare Groups
# ============================================
print("\n=== COMPARING GROUPS ===")
print("\nBilling Amount by Age Group:")
print(df.groupby('AgeGroup')['Billing Amount'].mean())

print("\nAdmission Type by Age Group (%):")
print(pd.crosstab(df['AgeGroup'], df['Admission Type'], normalize='index').round(3) * 100)

# ============================================
# YOUR CODE HERE: Create your own grouping!
# ============================================

print("\n=== DONE! ===")
print("Remember: Understanding WHAT you're doing and WHY matters more than memorizing syntax.")

=== DATASET OVERVIEW ===
Shape: (55500, 15)

Columns: ['Name', 'Age', 'Gender', 'Blood Type', 'Medical Condition', 'Date of Admission', 'Doctor', 'Hospital', 'Insurance Provider', 'Billing Amount', 'Room Number', 'Admission Type', 'Discharge Date', 'Medication', 'Test Results']

=== DATA VALIDATION ===
--- Age Validation ---
Age range: 13 to 89
Invalid ages (negative or >120): 0

--- Billing Validation ---
Negative billing: 108
Zero billing: 0

--- Date Validation ---
Failed date parsing: 0
Negative LOS: 0
Same-day discharge: 0

=== CREATING AGE GROUPS ===
Age Group Distribution:
AgeGroup
Middle-Aged (40-64)     20541
Young Adult (18-39)     17756
Senior (65+)            17087
Pediatric (Under 18)      116
Name: count, dtype: int64

=== COMPARING GROUPS ===

Billing Amount by Age Group:
AgeGroup
Middle-Aged (40-64)     25560.062391
Pediatric (Under 18)    28512.864205
Senior (65+)            25421.028108
Young Adult (18-39)     25609.720787
Name: Billing Amount, dtype: float64

Admission Type by Age Group (%):
Admission Type        Elective  Emergency  Urgent
AgeGroup
Middle-Aged (40-64)       34.1       32.5    33.4
Pediatric (Under 18)      29.3       41.4    29.3
Senior (65+)              33.0       33.3    33.7
Young Adult (18-39)       33.8       32.9    33.3

=== DONE! ===
Remember: Understanding WHAT you're doing and WHY matters more than memorizing syntax.